### ISSUE TITLE
Question: What if the custom kernel crashes

### ISSUE THREAD

**Issue by mafischer** [fabianishere/udm-kernel-tools#1]
What will happen if the kernel keeps crashing after enabling `udm-autoboot.service`? Will it auto disable after a couple failed boots?

**Comment by fabianishere** [comment]
The service will refuse to auto-boot if it sensed that the previous boot failed. 

To see how this mechanism works, see https://github.com/fabianishere/udm-kernel-tools/blob/195973f45abda6a5d38a7068d9267f804bb57b56/udm-bootctl#L212
