### ISSUE TITLE
Unknown qdisc "cake" in 4.19.152-edge1

### ISSUE THREAD

**Issue by kaybeng** [fabianishere/udm-kernel-tools#21]
Trying to configure cake for the UDM PRO v1.10.0 and was not successful.

`# uname -a`
`Linux ubnt 4.19.152-edge1 #1 SMP Fri Jul 9 18:01:33 UTC 2021 aarch64 GNU/Linux`
`# modprobe sch_cake`
`# /usr/sbin/tc qdisc add dev eth9 root cake bandwidth 900mbit`
`Unknown qdisc "cake", hence option "bandwidth" is unparsable`

May you guide me here. Thanks.

**Comment by fabianishere** [comment]
Could you check which version of `tc` (iproute2) you are using? It might be that the version installed in the UDM Pro does not support CAKE yet.

You could try to install iproute2 in UniFi OS and see if it works from there.

**Comment by kaybeng** [comment]
Installed iproute2 (4.9.0-1+deb9u1) in UniFi OS and encountered same error there.

**Comment by fabianishere** [comment]
You need to install iproute2 from `stretch-backports` for it to have CAKE support (4.20.0-2~bpo9+1)

**Comment by kaybeng** [comment]
Thank you. It is working within Unifi OS. However, I read elsewhere that such flows should be controlled from UbiOS instead?

[https://www.reddit.com/r/Ubiquiti/comments/m9psuk/udm_pro_and_sqm_esq_now/grodw5z/]

**Comment by fabianishere** [comment]
It might not be the cleanest solution, but it is difficult to get this working inside UbiOS (since you cannot install new packages there)

In the end, doing is from UniFi OS is the easiest way to get this working, so I wouldn’t worry to much about it.
