### ISSUE TITLE
IPTV script - There must be at least 1 Vif as upstream

### ISSUE THREAD

**Issue by coret** [fabianishere/udm-kernel-tools#22]
I have a similar setup as depicted in the diagram, so FTTH NTU (KPN) connected to the UDM/P (with UniFi OS Version 1.10.0, Controller Version 6.2.26 and Linux Dream-Machine-Pro 4.19.152-edge1 kernel), connected to a Unify switch, from port 8 the IPTV Decoder is connected. On my main LAN network (192.168.1.1/24, no VLAN) I have set the DHCP options from the table (Broadcast address set to 192.168.1.255) and enabled IGMP Snooping.

Below the output of the script and log:

```
# /mnt/data/on_boot.d/15-iptv.sh
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.

# podman logs -f iptv
udm-iptv: Obtaining IP address for VLAN interface...
udhcpc: started, v1.33.1
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc: sending discover
udhcpc failed to get a DHCP lease
udhcpc: no lease, forking to background
udm-iptv: NATing IPTV network ranges (if necessary)...
udm-iptv: Setting up igmpproxy..
udm-iptv: Starting igmpproxy..
adding VIF, Ix 0 Fl 0x0 IP 0x0101a8c0 br0, Threshold: 1, Ratelimit: 0
There must be at least 1 Vif as upstream.
udm-iptv: Obtaining IP address for VLAN interface...
udm-iptv: NATing IPTV network ranges (if necessary)...
ifup: interface iptv already configured
udm-iptv: Setting up igmpproxy..
udm-iptv: Starting igmpproxy..
adding VIF, Ix 0 Fl 0x0 IP 0x0101a8c0 br0, Threshold: 1, Ratelimit: 0
There must be at least 1 Vif as upstream.
udm-iptv: Obtaining IP address for VLAN interface...
udm-iptv: NATing IPTV network ranges (if necessary)...
ifup: interface iptv already configured
.....
```

What's causing this error? What am I missing?

**Comment by fabianishere** [comment]
It seems that you are not receiving a DHCP lease from the IPTV network (seeing the “failed to get DHCP lease”).

On what port did you connect the FTU? The RJ45 port or the SFP+ port?

**Comment by coret** [comment]
The RJ45 port (so the cable which connected the FTU to the Experia is now connected tothe WAN port (9) of the UDM/P). 
Internet is working alright for my network (so currently watching TV via the KPN iTV app and Chomecast as backup ;-).

**Comment by coret** [comment]
Ah, correction. So I did not connect the FTU, but the NTU (just learned the difference...). 
Do I need the NTU part and connect the FTU to the UDM/P over de SFP+ port?

**Comment by fabianishere** [comment]
Either way should work (so from the NTU to port 9 or from the FTU to port 10).

Could you share the on_boot script that you use for starting the container?

**Comment by coret** [comment]
I use the on_boot script as shown on https://github.com/fabianishere/udm-kernel-tools/blob/master/docs/iptv.md

Ok, just rebooted the UDM/P, and now IPTV works...
