### ISSUE TITLE
WAN Port on UDM/B

### ISSUE THREAD

**Issue by VeggieData** [fabianishere/udm-kernel-tools#34]
Thanks for this guide, and the work you've put into this. I've just been running through and have noticed that the WAN port for the UDM base model is set to port 4, but i think this should be port 5 by default

**Comment by fabianishere** [comment]
Do you mean port 5 or eth5?

**Comment by VeggieData** [comment]
Sorry, eth5. The 4 LAN ports are eth1-4 with the WAN on eth5. They're labeled Port 1-5 on the UDMB interface

**Comment by fabianishere** [comment]
Are you sure that is correct?

https://community.ui.com/questions/WAN-MAC-Address-on-Dream-Machine-Pro/3aeedc8d-b1fc-4f57-9e73-4fd8dbcd1ffc#answer/b0ac83c5-c84d-4ccd-b905-29d46be42008

Note that the WAN interfaces on the UDM/P start from 0, while the WAN ports start from 1, so there is an offset of 1.

**Comment by VeggieData** [comment]
Of course it does! I forgot about eth0. Its been a long couple of days trying to get this to work on a UDM base with BT IPTV in the UK. For some reason it all looks to go through fine but just won't work.

**Comment by fabianishere** [comment]
Usually there an issue with the settings entered during the installation. What are the settings you entered?

**Comment by VeggieData** [comment]
i've spent all weekend going back and forward over this, with no luck.

PTV_WAN_INTERFACE - eth4 
IPTV_WAN_RANGES - 234.0.0.0/8 224.0.0.0/4 109.159.247.0/24 239.0.0.0/8 233.0.0.0/8 (IPTV is vai BT in the UK)
IPTV_WAN_VLAN  - 0 as IPTV is on the same VLAN as other devices
IPTV_WAN_VLAN_INTERFACE - wasn't prompted
IPTV_LAN_INTERFACES - br0

I have a feeling by doing further reading, and looking at some of the other issues raised that this is to do with how BT handles their IPTV traffic in the UK.

I can get this to work via my EdgeRouter though, which was my previous solution to make this work until IGMP Proxy was supported on the UDM. With this the cable from my IPTV box goes into the Edge Router and everything else via the UDM. That was straight forward and only needed the following config (although i'm now running a double nat solution);

set protocols igmp-proxy interface eth0 alt-subnet 0.0.0.0/0
set protocols igmp-proxy interface eth0 role upstream
set protocols igmp-proxy interface switch0 alt-subnet 0.0.0.0/0
set protocols igmp-proxy interface switch0 role downstream
set interfaces ethernet eth0 address 10.255.255.255/32

**Comment by fabianishere** [comment]
Could it have something to do with you running a double NAT? Perhaps you could try sniffing the traffic from your decoder running behind a single NAT/dual NAT?

**Comment by VeggieData** [comment]
I take the double NAT out when trying the IGMP solution with the UDM, so it runs from the provider -> ONT -> UDM -> IPTV, which is when it doesn't work. 

Adding in the Edge Router between the ONT and UDM and using that for IGMP works, with the config above. I'll see if i can capture the traffic with both solutions and see if anything jumps out.

**Comment by bfayers** [comment]
Hey, @VeggieData I've got BTTV working with this on my UDM-Pro - this is what I did: https://github.com/fabianishere/udm-kernel-tools/issues/26#issuecomment-929968478

**Comment by VeggieData** [comment]
Thanks for that @bfayers. It worked a treat!
