### ISSUE TITLE
Issues with UDB and 1.11 firmware

### ISSUE THREAD

**Issue by DataAggregator** [fabianishere/udm-kernel-tools#35]
I've followed the guide, updating to the beta 1.11 firmware rather than using the custom kernel, but after going through all the steps its not working.

# sh -c "$(curl -s https://raw.githubusercontent.com/fabianishere/udm-kernel-too
ls/master/docs/iptv/install.sh)"
What is your WAN port?
  1. eth4 (WAN 1)
Enter WAN port [default: eth4]: 1
Is IPTV traffic carried over a separate VLAN? ([Y]es or [N]o): n
Which WAN interface carries your network traffic?
  1: eth4                  [IPv4 Address: None]
  2: ppp0                  [IPv4 Address: ]
Enter WAN interface [default: eth4]: 2
Which addresses are used for IPTV traffic?
Enter WAN ranges [default: 213.75.0.0/16 217.166.0.0/16]: 109.159.247.0/24 224.0.0.0/4
Which LANs are allowed to receive IPTV traffic?
  1: br0                   [IPv4 Address: 192.168.0.1]
  2: br2                   [IPv4 Address: 192.168.10.1]
  3: br3                   [IPv4 Address: 192.168.2.1]
Enter LAN interfaces separated by spaces [default: br0]: 1
Generated the following configuration:
  WAN Interface:      ppp0
  IPTV VLAN (WAN):    0
  IPTV Ranges (WAN):  109.159.247.0/24 224.0.0.0/4
  LAN Interfaces:     br0
IPTV boot script successfully installed at /mnt/data/on_boot.d/15-iptv.sh
See https://github.com/fabianishere/udm-kernel-tools/blob/master/docs/iptv.md for more information
Should the container be started immediately? ([Y]es or [N]o): y
Starting container...
d65894fa838838d6075c3a96cde3da726daf449f5f0bd0baacdf8ad0dbd76ded
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
ee4b5dd6778aa20b154ef2b203c1e6a13725d644d5063b5a8a4fb9fe82435bb3
udm-iptv: NATing IPTV network ranges (if necessary)...
iptables: No chain/target/match by that name.
udm-iptv: Setting up igmpproxy..
udm-iptv: Starting igmpproxy..

Running the debugging/troubleshooting commands ends up with the following;

# ip route list
 dev ppp0 proto kernel scope link src 86.166.7.17
192.168.0.0/24 dev br0 proto kernel scope link src 192.168.0.1
192.168.2.0/24 dev br3 proto kernel scope link src 192.168.2.1
192.168.10.0/24 dev br2 proto kernel scope link src 192.168.10.1
# ip -4 addr show dev iptv
Device "iptv" does not exist.

Any idea where its going wrong?

**Comment by fabianishere** [comment]
Since you have indicated that IPTV traffic is not carried over a separate VLAN, the "iptv" interface will not be created.

**Comment by DataAggregator** [comment]
ok, that makes sense. Its still not working as yet, but at least i can rule that out

**Comment by fabianishere** [comment]
You need to check whether you have satisfied all requirements for your ISP. 

Perhaps it is necessary to configure a static IP address for the IPTV network: https://community.bt.com/t5/YouView-from-BT/Inbound-IGMP-Multicast-for-BT-TV-Inconsistantly-Terminates/m-p/2105739/highlight/true#M59657

Otherwise, I suggest trying to use `tcpdump` to see what's happening on your network w.r.t. IPTV.
