### ISSUE TITLE
BT TV In the UK.

### ISSUE THREAD

**Issue by bfayers** [fabianishere/udm-kernel-tools#36]
Struggling to get the igmpproxy to work with BTTV here in the UK.

For a start, my UDM-Pro is on 1.10.0, running the latest udm-kernel edge1 custom kernel.

Using the information from this: https://community.ui.com/questions/Step-by-Step-guide-to-configuring-USG-to-work-with-BT-TV-Multicast-IP-TV-Services/b2c72429-7fcc-4a86-b3d8-0cbc443a4760

(I also followed the firewall rules instructions from ^)

My 15-iptv.sh looks like this:

```
# cat 15-iptv.sh
IPTV_WAN_INTERFACE="ppp1"
IPTV_WAN_RANGES="224.0.0.0/4 109.159.247.0/24"
IPTV_WAN_VLAN="0"
IPTV_WAN_DHCP_OPTIONS="-O staticroutes -V IPTV_RG"
IPTV_LAN_INTERFACES="br150"

if podman container exists iptv; then
  podman rm -f iptv
fi
podman run --network=host --privileged \
    --name iptv -i -d --restart on-failure:5 \
    -e IPTV_WAN_INTERFACE="$IPTV_WAN_INTERFACE" \
    -e IPTV_WAN_RANGES="$IPTV_WAN_RANGES" \
    -e IPTV_WAN_VLAN="$IPTV_WAN_VLAN" \
    -e IPTV_WAN_DHCP_OPTIONS="$IPTV_WAN_DHCP_OPTIONS" \
    -e IPTV_LAN_INTERFACES="$IPTV_LAN_INTERFACES" \
    -e IPTV_LAN_RANGES="" \
    fabianishere/udm-iptv -d -v
```

I see plenty of things like `Inserted route table entry for 233.89.188.1 on VIF #-1` and `Joining group 234.81.130.251 on interface ppp1` but I never see any routes added to `ip route list`

However, the BT TV Box never works.

It is worth noting that I am trying to do this on WAN2 hence ppp1. VLAN150, where my BTTV BOX is plugged in, is setup to route all traffic via wan2 with: `ip rule add from 192.168.150.0/24 lookup 202 prio 32100`

I suspect that most of the issue may come from it being on WAN2, I'm not sure. If you need any more info let me know.

**Comment by bfayers** [comment]
Similar to #25 I needed an IP on the wan (eth9) interface, not on the ppp1 interface.

Found via: https://forum.netgate.com/topic/118851/multicast-iptv-igmpproxy-issues-bt-tv-bt-sport-4k/2?_=1632855454838&lang=en-GB

added with: `ip addr add 10.20.30.1 dev eth9`
and changed the `IPTV_WAN_INTERFACE="eth9"`

Works great.... except for HD channels, which are a scrambled mess.

**Comment by fabianishere** [comment]
@bfayers Glad to hear that you got it working. My only suggestion for improving stability is to run the IPTV traffic over a separate VLAN (if you haven't done so).

**Comment by bfayers** [comment]
> 
> 
> @bfayers Glad to hear that you got it working. My only suggestion for improving stability is to run the IPTV traffic over a separate VLAN (if you haven't done so).
> 
> Also, as a suggestion, since (beta) firmware version 1.11.0 you don't need to run a custom kernel anymore to route multicast traffic.

👍 I'm already running the IPTV traffic over a separate VLAN, as for 1.11.0, I was just going to wait until that went stable and then remove the custom kernel and go from there.

As for now, HD channels seem to be working since my broadband brought itself back up to 50Mbps!
