### ISSUE TITLE
Root overlay location incorrect

### ISSUE THREAD

**Issue by JeremyAshton** [fabianishere/udm-kernel-tools#4]
I was digging into the root overlay option and found the README.md should be referencing `/overlay/root_ro/mnt/data/udm-kernel-tools/root` and not `/mnt/data/udm-kernel-tools/root`.

**Comment by fabianishere** [comment]
Well, both directories should be the same. 

In UbiOS, you should have mount at `/mnt/data`, which is where you can create these directory for the root overlay. 

Once the system boots into the custom kernel, the root filesystem is mounted at `/overlay/root_ro` (with the data mount at `/overlay/root_ro/mnt/data`. However, after that, a read-write overlay of the rootfs is mounted as `/`.

In essence, this means that `/mnt/data` and `/overlay/root_ro/mnt/data` point to the same thing.

**Comment by JeremyAshton** [comment]
Fair enough.  I guess I was confused a bit initially as I had to `mkdir -p /overlay/root_ro/mnt/data/udm-kernel-tools/root` and then it would mount correctly afterwards.  As in: https://github.com/fabianishere/udm-kernel-tools/blob/32f0816089c5187f4ff13e3c68f9ea2f6325c591/udm-init#L145-147

**Comment by fabianishere** [comment]
Good point. I think we should mention that in the documentation?

Were you getting any errors before creating the directory or did it just not show up?

**Comment by JeremyAshton** [comment]
No errors.  The directory structure was simply not there until the directories were created and a reboot occured.

**Comment by fabianishere** [comment]
Great, thanks for the info!

If you have the time, you can update your PR to include these steps. However, no worries if you don’t! Then I’ll update it at some point.
