### ISSUE TITLE
Breadcast address & some final steps

### ISSUE THREAD

**Issue by casperwolters** [fabianishere/udm-kernel-tools#7]
Hi,

First of all thanks for your guide it is great! 🤩

I have a few enhancement proposals:
- The broadcast address for the DHCP settings, where to get it? I now got it out of my "ip -4 ...." command, is this the place to get it?
- After you change the dhcp settings in the dashboard you have to rerun the " /mnt/data/on_boot.d/10-iptv.sh" command to get the etherface 8.4 known again, is this something can be automated?
- After previous step I also went into the shell again to reload the igmpproxy, not sure if it helps.
- Good to know, our iptv settop box didn't start updating his software without the steps above, not sure if you need to mention this.

**Comment by fabianishere** [comment]
Thank you for the feedback!

You spotted a mistake. Those steps should actually be switched around, because as soon as you make changes to your UniFi configuration, the VLAN interface will be removed and you need to run the script again. I will update the docs accordingly.

As for getting the broadcast address, it is usually obtained by setting all bits outside the subnet mask of your IP range, for instance:
```
192.168.X.1/24 => 192.168.X.255
192.168.0.1/16 => 192.168.255.255
```

**Comment by fabianishere** [comment]
f12970a should address the issues. Let me know if that answers all your questions!

**Comment by casperwolters** [comment]
Hi Fabian,

Great, looks good.

Another thanks for the scripts and functions! If I find anything new in the future while using this fix, I will let you know.

Personally I was thinking of making a bash script that regularly checks if there is a VLAN 4 present and if not, tries to create this (using a cron job or some sort). Not sure if this is possible but going to look into this, I will let you know when I succeed and will let you know or create a pull request.

Kind regards,

Cas Wolters

**Comment by fabianishere** [comment]
@casperwolters If you rename the IPTV VLAN interface from the default `eth8.4` to something else, then the UniFi controller will not remove it when reprovisioning the device. It think that solves the need for an update script.

See the updated guide for how to do this: https://github.com/fabianishere/udm-kernel-tools/blob/master/docs/iptv.md#creating-vlan-and-obtaining-ip-address
