### ISSUE TITLE
Troubleshoot update

### ISSUE THREAD

**Issue by casperwolters** [fabianishere/udm-kernel-tools#9]
While updating some configurations in your UDM settings (my case adding a G4 doorbell), the IGMP proxy that is running inside the unifi-os shell needs to be restarted.

For example:
When getting a "STB-NMC-400" error after a few seconds of seeing TV images  restarting the igmp proxy fixes this issue.

**Comment by fabianishere** [comment]
Thanks for the suggestion. I have updated the guide to suggest restarting igmpproxy as well.
